"""Index every recovery attempt, including failures and non-lookup diagnostics."""

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scc.provenance import atomic_json, file_digest


def build():
    entries, lines = [], [
        "# Retrieval recovery experiment registry", "",
        "Generated by `uv run --locked python scripts/report_recovery.py`.",
        "All results are exploratory validation, not final test results. Every",
        "attempt is included; query echo is explicitly excluded from lookup success.", "",
        "| Run | Task / encoding | Init std | Layers | Steps | Exact by category | Reordered exact | All queries, worst category/order | Gate |",
        "|---|---|---:|---:|---:|---|---|---:|---|",
    ]
    for protocol in sorted((ROOT / "runs").glob("online-*/protocol.json")):
        raw = json.loads(protocol.read_text())
        config = raw["contract"]["configuration"]
        result_path = protocol.parent / "result.json"
        result = json.loads(result_path.read_text()) if result_path.exists() else {}
        task, model = config["task"], config["training"]["model"]
        echo = task.get("echo_query", False)
        scores = {key: result.get(key, {}).get("scores", {})
                  for key in ("validation", "reordered_validation")}
        entry = {"run": protocol.parent.name, "configuration": config,
                 "protocol_sha256": file_digest(protocol),
                 "result_sha256": file_digest(result_path) if result else None,
                 "status": result.get("status", "running_or_incomplete"),
                 "diagnostic_only": echo, "scores": scores,
                 "actual_lookup_gate_passed": bool(result.get("development_gate_passed") and not echo),
                 "compute_seconds": result.get("compute_seconds"),
                 "parameter_count": result.get("parameter_count"),
                 "fresh_training_tables": result.get("fresh_training_tables"),
                 "exposure": result.get("exposure"), "language_after": result.get("language_after")}
        entries.append(entry)
        formatted = [", ".join(f"{name}: {value['exact_match']:.1%}" for name, value in items.items()) or "pending"
                     for items in scores.values()]
        worst = min((v["all_queries_exact"] for group in scores.values() for v in group.values()), default=0)
        gate = "echo only" if echo else "pass" if entry["actual_lookup_gate_passed"] else "fail" if result else "pending"
        encoding = "BPE" if config.get("tokenizer") else "bytes"
        task_name = f"{task['rendering']}, {task['value_length']} char, {encoding}"
        if config.get("natural_data"):
            task_name += ", text mix"
        lines.append(f"| [{entry['run']}](../runs/{entry['run']}/result.json) | {task_name} | "
                     f"{model.get('initializer_std', .02):g} | {model['layers']} | "
                     f"{result.get('completed_steps', '?')} | {formatted[0]} | {formatted[1]} | {worst:.1%} | {gate} |")
    atomic_json(ROOT / "artifacts/retrieval-recovery/experiment-registry.json", {
        "scope": "Local exploratory development; final test unused", "runs": entries})
    (ROOT / "reports/RETRIEVAL_RECOVERY_REGISTRY.md").write_text("\n".join(lines) + "\n")
    print(json.dumps({"runs": len(entries), "actual_lookup_passes": sum(e["actual_lookup_gate_passed"] for e in entries)}))


if __name__ == "__main__":
    build()
